### ISSUE TITLE
Versus screen - Hide undefined portraits 

### ISSUE THREAD

**Issue by shinlucho** [K4thos/Ikemen_GO#11]
During team arcade, when player choose more than one character and there isn't any configuration in `[VS Screen]` for `p3` `p4` and so on, ikemen shows all the portraits in the same place, but mugen only shows the first character portrait of the team:

mugen 1.0:
![mugen 1.0](https://vgy.me/nmYFXm.png)

ikemen:
![ikemen](https://vgy.me/Nj3RUT.png)

code:
```ini
[VS Screen]
...
p1.spr = 9000, 1
p1.offset =  20,31
p1.facing = 1
p1.scale = 1,1
p2.spr = 9000, 1
p2.offset = 299,31
p2.facing = -1
p2.scale = 1,1
```

I think ikemen should only show portraits that are defined with `p(num).spr = `

**Comment by Mike77154** [comment]
Bro, this multiportrair is a cool feature when you make a  KOF type game, but can be fixed changing position of portraits instead of removing it
