### ISSUE TITLE
[Request] Better Controller Connectivity

### ISSUE THREAD

**Issue by shinra358** [K4thos/Ikemen_GO#20]
Since this is a fighting series and it is competitive, it is a priority to have good controller connectivity. With xinput I believe once your controller disconnected, you couldn't play anymore unless you restarted it. Or once you started and then turn on your controller, it wouldnt connect because controller needs to be on before mugen is started. If you have friends come over and they have their own controller, it is a nightmare to restart the whole game so a new person can play.

So I'm requesting:

1.  Afterplugging support (turning controller on after the game is started)

2. Hotplugging (being able to disconnect and reconnect the controller during game and having it still work)

Thank you

**Comment by K4thos** [comment]
plugging in/out should work correctly in recent versions. Reopen the issue if you still have problems with controllers
