### ISSUE TITLE
Blood and Gore feature

### ISSUE THREAD

**Issue by PluocTheDragon** [K4thos/Ikemen_GO#24]
I'm not a Mortal Kombat-fan because this game is rated M for Mature. Since Kasumi Ninja on the Atari Jaguar does feature blood and gore level, parental lock, and password code. But I'm not interested of having a fighting game when they adding parental lock and password code to the blood and gore settings.

Since I requested to put blood and gore feature to Ikemen GO Plus, there are two unique things I may feature:

- Adjusting the gore level from Low, Medium, High or Off.
- Changes the blood colour from Red or Green.

Hope this game can have some enhancement.

**Comment by Mike77154** [comment]
This remembers me a lot of House of the dead games blood feature ;)

Maybe adding a code of features unlockables that the system acceds from the fightfx.def and fightfx.sff

**Comment by MrEmerik2000** [comment]
I have to say that the blood sprite FX from MK are animated frame by frame (or sprites by sprites) from High attacks. I perfer a smallest red (or green in Japan) pixelated dot for blood sprite FX by default.

When you hit hard enough, some bits of blood sprites flies off and falls on the battleground then slowly fades out.

**Comment by EmerikSteben** [comment]
Here's one example I made

![ikemen blood features sprites](https://user-images.githubusercontent.com/16625756/99194170-d684f400-274b-11eb-84d9-a343b2ff3f6c.png)

**Comment by K4thos** [comment]
duplicated
