### ISSUE TITLE
Coin-operated Mode

### ISSUE THREAD

**Issue by EmerikSteben** [K4thos/Ikemen_GO#25]
It would be nice if this game can be coin-operated like every 80s and 90s arcade game with some new features into the mix.

- You can set the option to insert a single quarter or double the price to play.
- You can set the game to be coin-operated or free play mode.
- This game can be available when you insert coins. No credits if unavailable.
- This feature can be triggered by a coin-operated USB board or something.

**Comment by Mike77154** [comment]
Maybe modding the lives control ((the continue screen lua script) adding a variable that adds one credit/live per push button

For example, in traditional winmugen we used to use front ends, for example one line that runing mugen shorcut demo mode for an eternal intro and demo play, one line running a mugen shorcut for arcade mode, and one line for interrupt 1st player in arcade mode with a mugen shorcut running in vs mode only

**Comment by Mike77154** [comment]
Mr emerick  maybe adding a counter add buton to the lives counter using button before compile

**Comment by MrEmerik2000** [comment]
![coin-op mode](https://user-images.githubusercontent.com/16625756/48580962-8c63a080-e8ee-11e8-9564-fa2df5c3bf93.png)

Here's one.

**Comment by K4thos** [comment]
implemented in v0.96
