### ISSUE TITLE
[Enhancement] Borderless Fullscreen & Full/Window Hotkey

### ISSUE THREAD

**Issue by shinra358** [K4thos/Ikemen_GO#30]
Would like to have borderless fullscreen mode to make it easier on the screen when creating and to have the ability to move back and forth between coding files and game without the screen flicker delay.

Also, the fullscreen/window hotkey seems to not work unless I'm missing something. That use to be alt+enter. Having it in the options is cool. But the hotkey is still needed or it will hinder devs workload. Decent PC games have both.

**Comment by K4thos** [comment]
both features are already in

**Comment by shinra358** [comment]
What's the hotkey? Alt+enter doesnt do anything
