### ISSUE TITLE
Fluidsynth or midi player compatible

### ISSUE THREAD

**Issue by Mike77154** [K4thos/Ikemen_GO#33]
It would be possible to add a midi player that uses user assigned soundfonts (.sf2) to generate ingame music prestablishin that soundfont in a lua script?

For example adding internal synthetizer (e.g fluidsynth library)

This feature will simulate an oldie 90s arcadevideogame type sound without rendering one by one mp3 chiptunelike without a 3rd party DAW

**Comment by K4thos** [comment]
https://github.com/Windblade-GR01/Ikemen-GO/issues/12
