### ISSUE TITLE
Single on teammenu.itemname tag

### ISSUE THREAD

**Issue by Gorilla65** [K4thos/Ikemen_GO#54]
Even if teammenu.itemname.single = Single is commented with semicolon the single option still appears.

**Comment by Gorilla65** [comment]
The same happens with simul and turns

**Comment by K4thos** [comment]
you are supposed to set them to blank value, not semicolon the: https://github.com/K4thos/Ikemen_GO/wiki#motif_order

**Comment by Gorilla65** [comment]
Oh, my bad I didn't paid attention to that, but if I leave the single tag blank Ikemen immediately closes.
