### ISSUE TITLE
Bug with tilespacing

### ISSUE THREAD

**Issue by Gorilla65** [K4thos/Ikemen_GO#55]
I'm trying to make an screenpack and now I need to use a scrolling transparent sprite, the transparency that type = normal offers is not good enough for the effect that I want, so I had to use type = anim, but with this the tilespacing parammeter ignores the y value and use the x value for both axis. And, for some reason the value that I have to put in the tilespacing have to be bigger if I use type = anim. Here's my code:
```
;[SelectBG 1] ;Scrolling background
;type  = normal
;spriteno = 100,1
;layerno = 0
;start = 0,0
;tile  = 1,1
;tilespacing = 30, 45
;mask = 1
;trans = add
;velocity = -1, -1

[SelectBG 1] ;Scrolling background
type  = anim
actionno = 100
layerno = 0
start = 0,0
tile  = 1,1
tilespacing = 250, 120
velocity = -1, -1

;========================
; BG Animations
;========================
[Begin Action 100] ;Kof scroll
100,1, 0,0, -1, , AS100D256
```

**Comment by K4thos** [comment]
just to be sure that you're using tilespacing correctly, please check out this topic: https://mugenguild.com/forum/topics/tiling-stage-animation-146058.0.html

**Comment by Gorilla65** [comment]
Hum... I didn't know about the difference in the coordinate starting point for normal and anim elements. Well, this is not a real problem, I just have to use the size of the sprite + the space that I want.
Still there's only one thing that is really annoyng: the y axis using the same value as defined in x.

**Comment by K4thos** [comment]
I've fixed it locally, although this will need testing. Strange that it was never reported before since tilespacing is not exactly obscure parameter. I will let this issue opened for now and let you know when a build that contains this fix will be ready for testing.

**Comment by Gorilla65** [comment]
Ok, thank you

**Comment by K4thos** [comment]
please test if the new build fixes this issue

**Comment by K4thos** [comment]
due to a problem discovered in v0.95, whole release has been taken down for now and v0.94 has been restored. So the request for testing will need to wait for now.

**Comment by Gorilla65** [comment]
Thanks, I will test later

**Comment by Gorilla65** [comment]
Now it works nicely
