### ISSUE TITLE
mid-air Platforms inside the stages

### ISSUE THREAD

**Issue by Shircan** [K4thos/Ikemen_GO#56]
Air platforms.

I think one of the things I've seen very interesting in creating scenarios and bonuses are the creation of air platforms.
While the creators used the character's own code with the help of elaborate helpers, but for many, create super smash-style fights or game recreations, among other things within the character code.

One of the things that the real mugen lacked was being able to create the scenarios with its own platforms, which, together with the things that are already there, would open up a world of possibilities.

Here are some links from experiments related to what I mean:

https://www.youtube.com/watch?v=lA_YbZLpIGo
https://www.youtube.com/watch?v=mtsuwvtyC9o
https://www.youtube.com/watch?v=DfKDzYkfQCE
https://www.youtube.com/watch?v=Hxcgei5sxQY

**Comment by K4thos** [comment]
ikemen go already natively platforms supports, including angled platforms. A person who implemented those parameters has not documented them though, but here is a list: https://github.com/K4thos/Ikemen_GO/wiki#sctrlchanged_projectile
If you successfully implement them please consider updating the above linked wiki article, so that everyone know how to use them.

**Comment by Shircan** [comment]
I was this time trying to implement it but I had no luck. -_-

so far the code tested were variants of the following:

```
[State 375, 1]
type = Projectile
affectteam = B
attr = N, NP
guardflag = MA
hitflag = MA
trigger1 =  Animelem =1

damage = 0
postype = p1
offset =  40,-20
projanim = 701
projscale = 1,0.5
projremove = 0
projhits =  99
projremovetime = 500
;=== test to implement ikemen platforms ===
platform = 1
platformFence   = 1
platformWidth    = 30
platformHeight   = 10
platformAngle   = 0
```
I saw in the code they have, starting from line 5953 there is the structure of how it would behave but I still cannot deduce how to make it work from the tests.

https://github.com/K4thos/Ikemen_GO/blob/main/src/char.go
