### ISSUE TITLE
Make debug to ignore Warning messages and helpers.

### ISSUE THREAD

**Issue by Orochikyocr** [K4thos/Ikemen_GO#60]
I really like some of the new features of the new debug system but (yeah there is a but) there are two suggestions I would like to make.

Put stateno, statetype and time in the lines that appears UP on the screen back again. Before I can check easily which stateno the character is, time and statetype of all characters at once even in 4v4 battles, now If I have two characters and the first character has five helpers and I need to press CTRL+D six-seven times until I get the second player info, imagine four players calling helpers, so I have to press CTRL+D like 30 times until I get the right character. 
Please make debug to ignore warnings, since I'm been working on a project I always got this message that an important helper I'm using for command buffering doesn't have the right target, I never was able to solve this on Mugen, and neither didn't care since everything works fine, but now in Ikemen Go that message spawn every single thick (as it does on Mugen but performance is worst on Ikemen Go) so when I turn on debug mode the framerate drops to 15-20 FPS and my CPU seems to overheat in order to maintain the demand of the debug mode. I'm afraid of turning on debug mode.
Also sometimes, or most times I don't care that much about what helpers are doing, so debug ignoring helpers could be a good option too just to get the info about the chars.

Maybe using the command line: Ikemen_Go -iw or something in the config.json  "debugoptions":  1-for ignoring warnings, 2 for ignoring helpers, 3- to ignoring both,  0- working as It is doing now.

**Comment by Orochikyocr** [comment]
For the record, these are the parameters that cause warning message in the debug mode if not put in the right order or not using cond()
Numenemy,numpartner,root. If any these are used before partner,(partner,id),enemy,enemy() llike 
not correct
type = changestate
triggerall = partner,stateno = 500
trigger1 =  roundstate
trigger1 = numpartner

Correct
type = changestate
triggerall = numpartner
trigger1 = partner,stateno = 500
trigger1 =  roundstate

In the case of root, is better to use root,alive first before calling any other root parameters.

I still have to test "parent" to see if it causes the same debug flood.

**Comment by K4thos** [comment]
stateno, statetype and time appearing at the top can be implemented locally by modifying statusInfo function in global.lua with stuff from actionInfo() and stateInfo() functions.

As for the second request v0.95 added ConsoleType option to config.json
