### ISSUE TITLE
Partner Projectiles behave as enemy projectiles  (guarding) 

### ISSUE THREAD

**Issue by thoj900** [K4thos/Ikemen_GO#65]
Holding back while partner does a projectile attack will put you into guarding state, thinking your partner projectile is enemy side.

https://www.youtube.com/watch?v=FxECOsDtiqo

**Comment by K4thos** [comment]
fixed: https://github.com/K4thos/Ikemen_GO/commit/e8aa099b2df136f83921bef5c703ed4cd7527b2f
