### ISSUE TITLE
Targetstate broken in 0.95.4 on TAG mode

### ISSUE THREAD

**Issue by Orochikyocr** [K4thos/Ikemen_GO#66]
I have these chars like Mature and Adel that have a movement when they take their opponent to a custom state through targetstate or directly in the hitdef by p1stateno and p2stateno parameters. 
When this char is a tag partner the player never gets to the custom state but 5100 common states.
![image](https://user-images.githubusercontent.com/42851314/88208047-e2cdca00-cc0d-11ea-8500-8a163ca0841a.png)
What I have tested 
My project using 0.95.4, with Adel, Maxima and Mature 624 A or C. 
Clean install using 0.95.4 using Rugal
The bug doesn't happen if any of the chars mentioned is the first player of the tag team. 
https://mega.nz/file/JAtBiRrL#r8XCJcC1va1uLQquYotHelc-kLxYn80QkAfcLiC_7jI 
Sharing Rugal for testing.

**Comment by K4thos** [comment]
not a bug, same thing happens in mugen 1.1:
![Untitled](https://user-images.githubusercontent.com/8928195/88212210-2d276900-cc57-11ea-8fd8-6c2720f8a495.png)

**Comment by Orochikyocr** [comment]
Following your own advice, I used Github to report this in the case that someone would show interest in fixing this. I'm surprised you quickly discard this as "not a bug" just because Mugen has it.
