### ISSUE TITLE
Build instructions are outdated

### ISSUE THREAD

**Issue by slzero-X** [K4thos/Ikemen_GO#67]
When looking into the files in the build folder, instead of 1.19.1 of OpenAL being used, it is 1.20.0, which means the build instructions haven't been updated since April, that is 3 months ago.

Due to this, it has caused one issue that hasn't been addressed by the main devs yet, which is that the executable compiled does not function and closes immediately due to an access violation when debugging it.

If any of the devs are currently active and available, please update the build instructions thank you.

**Comment by Windblade-GR01** [comment]
The builds are actually compiled with OpenAL 1.19, if OpenAL 1.20 is used the dependency does refuse to compile, I'll fix it so the next build are packaged with 1.19.
