### ISSUE TITLE
AfterImage not appearing in team modes? (Not sure if MUGEN limitation or bug)

### ISSUE THREAD

**Issue by thoj900** [K4thos/Ikemen_GO#70]
I tried to even set after image max to 1024, but afterimages wont appear if you go in teams. Not sure if this is an ikemen bug or mugen issue as a whole? 

Images: 
https://imgur.com/a/ZQD2gtC

The afterimage code I am using:

[state 3420]
type = AfterImage
trigger1 = time = 0
time = 60
length = 16
framegap = 3
trans = add1
ignorehitpause = 0

**Comment by K4thos** [comment]
can't reproduce it after pasting above code to kfm [Statedef 200] (Stand Light Punch)
![ikemen090](https://user-images.githubusercontent.com/8928195/89600232-d0849a80-d861-11ea-8f35-3f3650fe716a.png)
Also tested tag and simul matches with pots characters that use tons of afterimage effects and didn't notice any problems. Please try to recreate the issue with kfm to make testing easier.

**Comment by thoj900** [comment]
Closed. Sorry, seems it was my stupidity, I had some old global code for some reason changing afterimage time to 0. Works fine, Thanks
