### ISSUE TITLE
[Enhancement] Assert Special for opponent not face you or auto turn to you (SCTRL)

### ISSUE THREAD

**Issue by thoj900** [K4thos/Ikemen_GO#71]
This is usually a problem on add004 or tag system, where if a cross up happens (call an assist and the assist is behind the enemy and you are in front), the enemy will try to auto face the assisting partner. This usually doesnt happen in tag fighting games, and it kind of messes up some dynamic. 

I've asked this on forums, and tried looking at new state controllers in ikemen specifically, I don't think there is a sure fire way of doing this (spawning helpers etc). without some kind of fallback. Which is why I suggest maybe an sctrl that will treat you as some kind of non-player/non-helper so the enemy doesnt autoface you? Sorry if this already exists, maybe I missed it.

**Comment by K4thos** [comment]
discussed here: https://github.com/Windblade-GR01/Ikemen_GO/issues/163
