### ISSUE TITLE
(Bug) AffectTeam/Teamside does not affect Projectiles properly

### ISSUE THREAD

**Issue by thoj900** [K4thos/Ikemen_GO#72]
An issue in team modes only. If you launch a projectile with affectteam = b or new teamside parameter, the effects wont affect your team members projectiles depending on order of character selection. They won't hit. This works fine in Mugen 1.1, but seems to be a bug and work incorrectly in current Ikemen GO. It's quite extensive so please download these test files for yourself and watch the included demonstration video that goes IN DEPTH on what happens, how, and ways to re-produce the bug. You will notice in regular MUGEN everything works fine.

Video: https://streamable.com/dt1ogl

Test Files: https://drive.google.com/file/d/14XaoK9Mu0wtpP7VnKIayldoT4ASFudan/view?usp=sharing

**Comment by K4thos** [comment]
no idea what is causing it but at least can confirm that the same problem always existed in ikemen go (tested on builds with only Suehiro's code) so it's unrelated to changes introduced by commit that added TeamSide parameter to hitdef.

**Comment by K4thos** [comment]
discussed here: https://github.com/Windblade-GR01/Ikemen_GO/issues/164
