### ISSUE TITLE
Text layers get cropped in storyboards + incorrect text offset

### ISSUE THREAD

**Issue by XGargoyle79** [K4thos/Ikemen_GO#75]
Text layers in storyboards get cropped as if they are apparently using a different localcoord from the rest of the BG elements.
In mugen, the storyboard shows the full text (bottom blue):
![mugen011](https://user-images.githubusercontent.com/70286523/91339654-14225280-e7d7-11ea-8801-2237edc38866.png)

However, the same storyboard in ikemen results in cropped text at the bottom, as if there was either a window mask applied or as if the text layers were using a different localcoord:
![ikemen031](https://user-images.githubusercontent.com/70286523/91339809-4b90ff00-e7d7-11ea-80f6-2098ea3ca83b.png)

This "masking" only affects the text layer. Sprites are not cropped or trimmed by it, so it seems the bug lies on the text rendering engine:
![ikemen032](https://user-images.githubusercontent.com/70286523/91339960-83984200-e7d7-11ea-9908-c0dec3ce9540.png)

Offset X position on the text layer also seems to be incorrect in Ikemen, as you can compare from both screenshots.

Files that you can use for testing:
[http://xgargoyle.mugenguild.com/storyboard.zip](url)

Game runs at 1280x800, by the way.

Let me know if you need any extra detail. Thanks

**Comment by K4thos** [comment]
reuploaded since the above link no longer works
[storyboard.zip](https://github.com/K4thos/Ikemen_GO/files/5255984/storyboard.zip)

**Comment by K4thos** [comment]
fixed locally, it should work correctly in the next major release

**Comment by K4thos** [comment]
fixed in v0.96
