### ISSUE TITLE
[ENHANCEMENT] Z-Depth

### ISSUE THREAD

**Issue by shinra358** [K4thos/Ikemen_GO#76]
I would like a variable that is a Z-depth. Characters with different z-depth will not be able to hit or touch each other. Z-depth of the same number will allow characters to interact with each other. This is so that users can create beat em up time games or features such as foreground/background fighting like guilty gear isuka and fatal fury games. Doing it without this currently is very limited and increases the size of the anim files. This would add more functionality.

Ex: 
Type=Z-depth
Trigger1 = 1
Value = 5 (0 equals normal ground. negative value equals forground. positive number equals background)

can also be used as a trigger like this:
Type = HitDef
Trigger1= Z-depth = 0 && enemy, Z-depth=[-2,2]    (means move is able to hit chars who have a value of -2, -1, 0, 1, and 2 for z-depth if you are at z-depth 0)

Normal mugen has a problem/bug deternmining which enemy is near for this to work in normal mugen. If that were fixed, I could just use a regular variable for this.

**Comment by Windblade-GR01** [comment]
Already done.
It uses the DosMugen implementation.
It will be in the next version.

**Comment by shinra358** [comment]
Wow, shweet!
