### ISSUE TITLE
[Request] XbrZ Scaler

### ISSUE THREAD

**Issue by shinra358** [K4thos/Ikemen_GO#8]
I would like to request the xbrz scaler so that we can keep  our content at 640x480 rezzed items, keeping our game sizes down while  at the same time erraticating pixelation and keeping our presentation  beautiful. 

xbrz source: https://sourceforge.net/p/xbrz/forums/general/ 

examples:
 https://s6.postimg.cc/6feleg801/retroarch_2016-11-23_19-27-06.png 
https://s6.postimg.cc/9uhuy9e2p/e_PSXe_2016-11-16_14-32-29.png 
https://s6.postimg.cc/ntytmq54x/retroarch_2016-11-23_19-27-28.png
 https://s6.postimg.cc/9c1meqdtt/retroarch_2016-11-23_19-45-30.png
 https://s6.postimg.cc/cf2ci3ssh/retroarch_2016-11-23_19-25-41.png
--

**Comment by K4thos** [comment]
the engine has external shaders support, so you can use it already

**Comment by shinra358** [comment]
Xbrz is a scaler. Not a shader. It cannot be coded externally. It must be internal. Any external xbrz is an immitation and doesnt wrk as it should.
